name: Publish Development Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      # Este paso siempre funciona y te da el archivo en el Summary
      - name: Upload Artifact to Summary
        uses: actions/upload-artifact@v4
        with:
          name: xA-Addon 
          path: build/libs/*.jar
          retention-days: 5

      # Crea o actualiza la Release
      # Usamos 'fail_on_unmatched_files: false' para evitar errores tontos
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: snapshot
          name: Dev Build
          prerelease: true
          files: build/libs/*.jar
          overwrite_files: true
          fail_on_unmatched_files: false
          make_latest: true
          
